In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Internship_Sales_Cleaned.xlsx to Internship_Sales_Cleaned.xlsx

In [ ]:
import pandas as pd

file = "Internship_Sales_Cleaned.xlsx"

excel = pd.ExcelFile(file)

excel.sheet_names

['Cleaned Data', 'Raw Data', 'Instructions']

In [ ]:
df = pd.read_excel("Internship_Sales_Cleaned.xlsx", sheet_name="Cleaned Data")

df.head()

,Order ID,Order Date,Customer ID,Customer Name,Region,Segment,Product Name,Category,Quantity,Discount,Sales,Profit
0,ORD-1001,2025-09-28,CUST-171,Customer 61,North,Home Office,Bookshelf,Furniture,4,0.20,20800.0,2080.0
1,ORD-1002,2025-03-29,CUST-123,Customer 3,South,Consumer,Monitor,Electronics,3,0.10,40500.0,8100.0
2,ORD-1003,2025-07-11,CUST-159,Customer 21,North,Corporate,Smartphone,Electronics,4,0.05,83600.0,20240.0
3,ORD-1004,2025-12-11,CUST-148,Customer 59,East,Corporate,Desk,Furniture,5,0.15,51000.0,7800.0
4,ORD-1005,2025-12-30,CUST-154,Customer 64,North,Home Office,Notebook,Stationery,4,0.10,900.0,180.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       398 non-null    object
 1   Order Date     398 non-null    datetime64[ns]
 2   Customer ID    398 non-null    object
 3   Customer Name  397 non-null    object
 4   Region         397 non-null    object
 5   Segment        398 non-null    object
 6   Product Name   397 non-null    object
 7   Category       398 non-null    object
 8   Quantity       398 non-null    int64
 9   Discount       397 non-null    float64
 10  Sales          397 non-null    float64
 11  Profit         398 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 37.4+ KB

In [ ]:
df.isnull().sum()

Order ID         0
Order Date       0
Customer ID      0
Customer Name    1
Region           1
Segment          0
Product Name     1
Category         0
Quantity         0
Discount         1
Sales            1
Profit           0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Order ID,Order Date,Customer ID,Customer Name,Region,Segment,Product Name,Category,Quantity,Discount,Sales,Profit
30,ORD-1031,2025-08-28,CUST-115,NaN,West,Home Office,Desk,Furniture,6,0.10,64800.0,12960.0
87,ORD-1088,2025-05-14,CUST-157,Customer 44,NaN,Consumer,Mouse,Electronics,1,0.20,720.0,72.0
142,ORD-1143,2025-09-11,CUST-167,Customer 66,South,Consumer,Office Chair,Furniture,3,NaN,25500.0,7140.0
211,ORD-1212,2025-02-06,CUST-159,Customer 48,North,Consumer,Office Chair,Furniture,2,0.05,NaN,3910.0
322,ORD-1323,2025-04-07,CUST-103,Customer 4,East,Consumer,NaN,Electronics,7,0.15,14875.0,2275.0

In [ ]:
# Fill missing values using logical values from the existing data

df.loc[30, "Customer Name"] = "Customer 15"
df.loc[87, "Region"] = "West"
df.loc[142, "Discount"] = 0.10
df.loc[211, "Sales"] = 39100.0
df.loc[322, "Product Name"] = "Keyboard"

print("Missing values filled successfully!")

Missing values filled successfully!

In [ ]:
df.isnull().sum()

Order ID         0
Order Date       0
Customer ID      0
Customer Name    0
Region           0
Segment          0
Product Name     0
Category         0
Quantity         0
Discount         0
Sales            0
Profit           0
dtype: int64

In [ ]:
df.describe()

,Order Date,Quantity,Discount,Sales,Profit
count,398,398.000000,398.000000,398.000000,398.000000
mean,2025-06-28 02:46:25.929648128,3.849246,0.114447,36957.418342,7415.845477
min,2025-01-01 00:00:00,-2.000000,0.000000,-500.000000,-1000.000000
25%,2025-04-04 06:00:00,2.000000,0.050000,5400.000000,909.000000
50%,2025-06-28 12:00:00,4.000000,0.100000,15300.000000,2944.000000
75%,2025-09-18 18:00:00,6.000000,0.150000,46750.000000,9127.500000
max,2025-12-30 00:00:00,7.000000,7.500000,365750.000000,88550.000000
std,NaN,1.998081,0.378115,53475.869573,11250.256619

In [ ]:
df[df["Quantity"] < 0]

,Order ID,Order Date,Customer ID,Customer Name,Region,Segment,Product Name,Category,Quantity,Discount,Sales,Profit
260,ORD-1261,2025-09-21,CUST-142,Customer 76,North,Consumer,Laptop,Electronics,-2,0.15,233750.0,35750.0

In [ ]:
df[df["Product Name"] == "Laptop"][["Quantity", "Discount", "Sales", "Profit"]]

     Quantity  Discount     Sales   Profit
12          1      0.00   55000.0  15400.0
15          7      0.20  308000.0  30800.0
18          4      0.20  176000.0  17600.0
41          1      0.15   46750.0   7150.0
43          5      0.15  233750.0  35750.0
44          1      0.15   46750.0   7150.0
68          2      0.10   99000.0  19800.0
93          1      0.00   55000.0  15400.0
101         1      0.05   52250.0  12650.0
120         7      0.05  365750.0  88550.0
139         1      0.05   52250.0  12650.0
141         4      0.10  198000.0  39600.0
157         4      0.15  187000.0  28600.0
159         5      0.20  220000.0  22000.0
160         6      0.10  297000.0  59400.0
172         2      0.10   99000.0  19800.0
178         2      0.20   88000.0   8800.0
197         5      0.20  220000.0  22000.0
200         5      0.00  275000.0  77000.0
212         2      0.20   88000.0   8800.0
222         2      0.00  110000.0  30800.0
235         5      0.05  261250.0  63250.0
251         3      0.00  165000.0  46200.0
260        -2      0.15  233750.0  35750.0
262         1      0.15   46750.0   7150.0
294         3      0.15  140250.0  21450.0
315         4      0.00  220000.0  61600.0
365         1      0.15   46750.0   7150.0
385         7      0.20  308000.0  30800.0
395         4      0.00  220000.0  61600.0

In [ ]:
df.loc[260, "Quantity"] = 5

print(df.loc[260])

Order ID                    ORD-1261
Order Date       2025-09-21 00:00:00
Customer ID                 CUST-142
Customer Name            Customer 76
Region                         North
Segment                     Consumer
Product Name                  Laptop
Category                 Electronics
Quantity                           5
Discount                        0.15
Sales                       233750.0
Profit                       35750.0
Name: 260, dtype: object

In [ ]:
df[df["Discount"] > 1]

,Order ID,Order Date,Customer ID,Customer Name,Region,Segment,Product Name,Category,Quantity,Discount,Sales,Profit
275,ORD-1276,2025-10-06,CUST-174,Customer 1,West,Corporate,Smartphone,Electronics,5,7.5,110000.0,30800.0

In [ ]:
df[df["Product Name"] == "Smartphone"][["Quantity", "Discount", "Sales", "Profit"]]

     Quantity  Discount     Sales   Profit
2           4      0.05   83600.0  20240.0
9           2      0.15   37400.0   5720.0
27          4      0.20   70400.0   7040.0
39          2      0.10   39600.0   7920.0
57          4      0.05   83600.0  20240.0
66          1      0.15   18700.0   2860.0
69          5      0.10   99000.0  19800.0
71          5      0.10   99000.0  19800.0
89          7      0.00  154000.0  43120.0
96          7      0.00  154000.0  43120.0
102         6      0.10  118800.0  23760.0
106         4      0.00   88000.0  24640.0
109         5      0.10   99000.0  19800.0
131         2      0.20   35200.0   3520.0
148         1      0.00   22000.0   6160.0
167         7      0.05  146300.0  35420.0
174         7      0.20  123200.0  12320.0
188         1      0.15   18700.0   2860.0
208         3      0.00   66000.0  18480.0
209         4      0.05   83600.0  20240.0
218         4      0.05   83600.0  20240.0
231         4      0.10   79200.0  15840.0
267         7      0.15  130900.0  20020.0
270         2      0.00   44000.0  12320.0
275         5      7.50  110000.0  30800.0
297         3      0.05   62700.0  15180.0
303         7      0.15  130900.0  20020.0
309         1      0.20   17600.0   1760.0
312         5      0.10   99000.0  19800.0
332         2      0.15   37400.0   5720.0
333         3      0.00   66000.0  18480.0
339         3      0.00   66000.0  18480.0
345         5      0.20   88000.0   8800.0
355         5      0.00  110000.0  30800.0
397         7      0.15  130900.0  20020.0

In [ ]:
df.loc[275, "Discount"] = 0.00

print(df.loc[275])

Order ID                    ORD-1276
Order Date       2025-10-06 00:00:00
Customer ID                 CUST-174
Customer Name             Customer 1
Region                          West
Segment                    Corporate
Product Name              Smartphone
Category                 Electronics
Quantity                           5
Discount                         0.0
Sales                       110000.0
Profit                       30800.0
Name: 275, dtype: object

In [ ]:
df[df["Sales"] < 0]

,Order ID,Order Date,Customer ID,Customer Name,Region,Segment,Product Name,Category,Quantity,Discount,Sales,Profit
288,ORD-1289,2025-10-25,CUST-155,Customer 36,West,Corporate,Bookshelf,Furniture,7,0.0,-500.0,12740.0

In [ ]:
df[df["Product Name"] == "Bookshelf"][["Quantity", "Discount", "Sales", "Profit"]]

     Quantity  Discount    Sales   Profit
0           4      0.20  20800.0   2080.0
26          2      0.10  11700.0   2340.0
50          2      0.10  11700.0   2340.0
51          1      0.15   5525.0    845.0
56          4      0.20  20800.0   2080.0
86          1      0.10   5850.0   1170.0
158         3      0.10  17550.0   3510.0
192         1      0.10   5850.0   1170.0
196         5      0.20  26000.0   2600.0
217         2      0.05  12350.0   2990.0
241         4      0.00  26000.0   7280.0
252         2      0.10  11700.0   2340.0
254         2      0.15  11050.0   1690.0
264         3      0.20  15600.0   1560.0
277         7      0.20  36400.0   3640.0
283         7      0.20  36400.0   3640.0
288         7      0.00   -500.0  12740.0
289         6      0.00  39000.0  10920.0
290         6      0.20  31200.0   3120.0
298         4      0.10  23400.0   4680.0
306         4      0.10  23400.0   4680.0
313         4      0.00  26000.0   7280.0
324         2      0.20  10400.0   1040.0
327         2      0.20  10400.0   1040.0
335         3      0.00  19500.0   5460.0
346         7      0.15  38675.0   5915.0
353         3      0.10  17550.0   3510.0
356         6      0.10  35100.0   7020.0
370         2      0.10  11700.0   2340.0
376         6      0.05  37050.0   8970.0
377         5      0.05  30875.0   7475.0
393         5      0.15  27625.0   4225.0

In [ ]:
df.loc[288, "Sales"] = 36400.0

print(df.loc[288])

Order ID                    ORD-1289
Order Date       2025-10-25 00:00:00
Customer ID                 CUST-155
Customer Name            Customer 36
Region                          West
Segment                    Corporate
Product Name               Bookshelf
Category                   Furniture
Quantity                           7
Discount                         0.0
Sales                        36400.0
Profit                       12740.0
Name: 288, dtype: object

In [ ]:
df[df["Profit"] < 0]

,Order ID,Order Date,Customer ID,Customer Name,Region,Segment,Product Name,Category,Quantity,Discount,Sales,Profit
310,ORD-1311,2025-07-15,CUST-154,Customer 6,East,Corporate,Keyboard,Electronics,6,0.05,10260.0,-1000.0

In [ ]:
df[df["Product Name"] == "Keyboard"][["Quantity", "Discount", "Sales", "Profit"]]

     Quantity  Discount    Sales  Profit
8           2      0.15   3060.0   468.0
35          4      0.00   7200.0  2016.0
37          6      0.00  10800.0  3024.0
40          1      0.20   1440.0   144.0
63          5      0.15   7650.0  1170.0
75          4      0.20   5760.0   576.0
77          3      0.20   4320.0   432.0
83          4      0.15   6120.0   936.0
116         1      0.00   1800.0   504.0
121         1      0.15   1530.0   234.0
126         7      0.05  11970.0  2898.0
132         1      0.20   1440.0   144.0
144         5      0.15   7650.0  1170.0
145         4      0.20   5760.0   576.0
151         6      0.00  10800.0  3024.0
161         1      0.20   1440.0   144.0
169         3      0.05   5130.0  1242.0
194         5      0.00   9000.0  2520.0
225         1      0.10   1620.0   324.0
226         2      0.15   3060.0   468.0
228         6      0.10   9720.0  1944.0
240         2      0.05   3420.0   828.0
263         2      0.05   3420.0   828.0
285         5      0.15   7650.0  1170.0
286         6      0.05  10260.0  2484.0
299         5      0.00   9000.0  2520.0
308         2      0.20   2880.0   288.0
310         6      0.05  10260.0 -1000.0
314         2      0.05   3420.0   828.0
316         3      0.10   4860.0   972.0
317         1      0.15   1530.0   234.0
318         2      0.20   2880.0   288.0
322         7      0.15  14875.0  2275.0
328         1      0.10   1620.0   324.0
337         7      0.10  11340.0  2268.0
348         3      0.05   5130.0  1242.0
357         4      0.05   6840.0  1656.0
359         1      0.15   1530.0   234.0
363         3      0.20   4320.0   432.0
364         1      0.10   1620.0   324.0
372         5      0.15   7650.0  1170.0

In [ ]:
df.loc[310, "Profit"] = 2484.0

print(df.loc[310])

Order ID                    ORD-1311
Order Date       2025-07-15 00:00:00
Customer ID                 CUST-154
Customer Name             Customer 6
Region                          East
Segment                    Corporate
Product Name                Keyboard
Category                 Electronics
Quantity                           6
Discount                        0.05
Sales                        10260.0
Profit                        2484.0
Name: 310, dtype: object

In [ ]:
df.describe()

,Order Date,Quantity,Discount,Sales,Profit
count,398,398.000000,398.000000,398.000000,398.000000
mean,2025-06-28 02:46:25.929648128,3.866834,0.095603,37050.131910,7424.599246
min,2025-01-01 00:00:00,1.000000,0.000000,200.000000,20.000000
25%,2025-04-04 06:00:00,2.000000,0.050000,5400.000000,936.000000
50%,2025-06-28 12:00:00,4.000000,0.100000,15675.000000,2944.000000
75%,2025-09-18 18:00:00,6.000000,0.150000,46750.000000,9127.500000
max,2025-12-30 00:00:00,7.000000,0.200000,365750.000000,88550.000000
std,NaN,1.977163,0.072467,53442.741698,11245.046031

In [ ]:
df.to_excel("Final_Cleaned_Sales_Data.xlsx", index=False)

print("Final cleaned file created successfully!")

Final cleaned file created successfully!

In [ ]:
import os

os.path.exists("Final_Cleaned_Sales_Data.xlsx")

True

In [ ]:
total_sales = df["Sales"].sum()

print("Total Sales:", total_sales)

Total Sales: 14745952.5

In [ ]:
total_profit = df["Profit"].sum()

print("Total Profit:", total_profit)

Total Profit: 2954990.5

In [ ]:
number_of_orders = df["Order ID"].nunique()

print("Number of Orders:", number_of_orders)

Number of Orders: 398

In [ ]:
profit_margin = (total_profit / total_sales) * 100

print("Profit Margin:", profit_margin, "%")

Profit Margin: 20.039332827092725 %

In [ ]:
sales_by_region = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

print(sales_by_region)

Region
North    4159915.0
East     4103362.5
West     3605567.5
South    2837407.5
NORTH      29700.0
south      10000.0
Name: Sales, dtype: float64

In [ ]:
df["Region"] = df["Region"].str.strip().str.title()

print(df["Region"].value_counts())

Region
North    115
East     106
West      94
South     83
Name: count, dtype: int64

In [ ]:
sales_by_region = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

print(sales_by_region)

Region
North    4189615.0
East     4103362.5
West     3605567.5
South    2847407.5
Name: Sales, dtype: float64

In [ ]:
sales_by_category = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

print(sales_by_category)

Category
Electronics    10915020.0
Furniture       3572000.0
Accessories      228330.0
Stationery        27362.5
electronics        3240.0
Name: Sales, dtype: float64

In [ ]:
df["Category"] = df["Category"].str.strip().str.title()

print(df["Category"].value_counts())

Category
Electronics    229
Furniture      105
Accessories     34
Stationery      30
Name: count, dtype: int64

In [ ]:
sales_by_category = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

print(sales_by_category)

Category
Electronics    10918260.0
Furniture       3572000.0
Accessories      228330.0
Stationery        27362.5
Name: Sales, dtype: float64

In [ ]:
df["Month"] = df["Order Date"].dt.to_period("M")

monthly_sales = df.groupby("Month")["Sales"].sum()

print(monthly_sales)

Month
2025-01    1267007.5
2025-02     754415.0
2025-03    1170310.0
2025-04    1446812.5
2025-05    1029845.0
2025-06    1756400.0
2025-07    1115645.0
2025-08    1523172.5
2025-09    1394087.5
2025-10     839070.0
2025-11    1505240.0
2025-12     943947.5
Freq: M, Name: Sales, dtype: float64

In [ ]:
top_10_products = (
    df.groupby("Product Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_10_products)

Product Name
Laptop          4914250.0
Smartphone      2896300.0
Desk            1704600.0
Monitor         1461000.0
Office Chair    1173850.0
Printer          979550.0
Bookshelf        693550.0
Headphones       344125.0
Keyboard         231775.0
Backpack         231570.0
Name: Sales, dtype: float64

In [ ]:
region_sales = df.groupby("Region")["Sales"].sum().reset_index()

print(region_sales)

  Region      Sales
0   East  4103362.5
1  North  4189615.0
2  South  2847407.5
3   West  3605567.5

In [ ]:
df.to_excel("Final_Cleaned_Sales_Data.xlsx", index=False)

print("Final file updated successfully!")

Final file updated successfully!

In [ ]:
df.to_excel("Final_Cleaned_Sales_Data.xlsx", index=False)

In [ ]:
from google.colab import files

files.download("Final_Cleaned_Sales_Data.xlsx")